services:
  app:
    build:
      context: .
    image: georag-api
    depends_on:
      postgres:
        condition: service_started
      s3:
        condition: service_started
      s3-init:
        condition: service_completed_successfully
    environment:
      DEV_MODE: "${DEV_MODE:-true}"
      LOG_LEVEL: "${LOG_LEVEL:-DEBUG}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      DATABASE_DSN: "${DATABASE_DSN_DOCKER:-postgresql+asyncpg://postgres:postgres@postgres:5432/georag}"
      DATABASE_ECHO: "${DATABASE_ECHO:-false}"
      S3_BUCKET: "${S3_BUCKET:-geo-images}"
      S3_ENDPOINT_URL: "${S3_ENDPOINT_URL:-http://s3:9000}"
      S3_REGION: "${S3_REGION:-ru-central1}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-localstack}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-localstack}"
      S3_USE_SSL: "${S3_USE_SSL:-false}"
      S3_IMAGES_PREFIX: "${S3_IMAGES_PREFIX:-images}"
      S3_FEATURES_PREFIX: "${S3_FEATURES_PREFIX:-features/local}"
      S3_GLOBAL_PREFIX: "${S3_GLOBAL_PREFIX:-features/global}"
      FEATURE_MAX_KEYPOINTS: "${FEATURE_MAX_KEYPOINTS:-4096}"
      LOCAL_FEATURE_TYPE: "${LOCAL_FEATURE_TYPE:-superpoint_max}"
      GLOBAL_DESCRIPTOR_TYPE: "${GLOBAL_DESCRIPTOR_TYPE:-netvlad}"
      MATCHER_TYPE: "${MATCHER_TYPE:-lightglue}"
      RETRIEVAL_CANDIDATES: "${RETRIEVAL_CANDIDATES:-32}"
      GLOBAL_SCORE_WEIGHT: "${GLOBAL_SCORE_WEIGHT:-0.35}"
      LOCAL_SCORE_WEIGHT: "${LOCAL_SCORE_WEIGHT:-0.65}"
      GEOMETRY_SCORE_WEIGHT: "${GEOMETRY_SCORE_WEIGHT:-0.25}"
      MAX_SEARCH_RESULTS: "${MAX_SEARCH_RESULTS:-50}"
      INDEX_REFRESH_INTERVAL: "${INDEX_REFRESH_INTERVAL:-7200}"
      COMPUTE_DEVICE: "${COMPUTE_DEVICE:-}"
      NOMINATIM_USER_AGENT: "${NOMINATIM_USER_AGENT:-GeoRAG/1.0 (+https://example.com)}"
      NOMINATIM_TIMEOUT: "${NOMINATIM_TIMEOUT:-50}"
      MAPILLARY_TOKEN: "${MAPILLARY_TOKEN:-}"
    ports:
      - "8000:8000"
    volumes:
      - nn_models:/models
      - ./train_data:/app/train_data

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-georag}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY:-localstack}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY:-localstack}"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data

  s3-init:
    image: minio/mc:latest
    depends_on:
      s3:
        condition: service_started
    environment:
      S3_ENDPOINT_URL: "${S3_ENDPOINT_URL:-http://s3:9000}"
      S3_BUCKET: "${S3_BUCKET:-geo-images}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-localstack}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-localstack}"
    entrypoint: >-
      /bin/sh -c "
      set -euo pipefail;
      until mc alias set local "$${S3_ENDPOINT_URL}" "$${S3_ACCESS_KEY}" "$${S3_SECRET_KEY}"; do
        echo 'Waiting for MinIO...';
        sleep 1;
      done;
      mc mb --ignore-existing local/$${S3_BUCKET};
      mc anonymous set download local/$${S3_BUCKET};
      "
    restart: "no"

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      OLLAMA_KEEP_ALIVE: "${OLLAMA_KEEP_ALIVE:-24h}"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  nn_models:
  s3_data:
  ollama_data:
