version: "3.9"

services:
  app:
    build:
      context: .
    image: georag-api
    depends_on:
      postgres:
        condition: service_started
      s3:
        condition: service_started
      s3-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DEV_MODE: "${DEV_MODE:-false}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      DATABASE_DSN: "${DATABASE_DSN:-postgresql+asyncpg://postgres:postgres@postgres:5432/georag}"
      DATABASE_ECHO: "${DATABASE_ECHO:-false}"
      S3_BUCKET: "${S3_BUCKET:-georag-images}"
      S3_ENDPOINT_URL: "${S3_ENDPOINT_URL:-http://s3:9000}"
      S3_REGION: "${S3_REGION:-us-east-1}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-minioadmin}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-minioadmin}"
      S3_USE_SSL: "${S3_USE_SSL:-false}"
      S3_FEATURES_PREFIX: "${S3_FEATURES_PREFIX:-features/local}"
      S3_GLOBAL_PREFIX: "${S3_GLOBAL_PREFIX:-features/global}"
      LOCAL_FEATURE_TYPE: "${LOCAL_FEATURE_TYPE:-superpoint_max}"
      GLOBAL_DESCRIPTOR_TYPE: "${GLOBAL_DESCRIPTOR_TYPE:-netvlad}"
      MATCHER_TYPE: "${MATCHER_TYPE:-lightglue}"
      RETRIEVAL_CANDIDATES: "${RETRIEVAL_CANDIDATES:-32}"
      GLOBAL_SCORE_WEIGHT: "${GLOBAL_SCORE_WEIGHT:-0.35}"
      LOCAL_SCORE_WEIGHT: "${LOCAL_SCORE_WEIGHT:-0.65}"
      PREFER_GPU: "${PREFER_GPU:-false}"
    ports:
      - "8000:8000"
    volumes:
      - hf_models:/models

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-georag}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY:-minioadmin}"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data

  s3-init:
    image: minio/mc:latest
    depends_on:
      s3:
        condition: service_started
    environment:
      S3_ENDPOINT_URL: "${S3_ENDPOINT_URL:-http://s3:9000}"
      S3_BUCKET: "${S3_BUCKET:-georag-images}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-minioadmin}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-minioadmin}"
    entrypoint: >-
      /bin/sh -c "
      set -euo pipefail;
      until mc alias set local "$${S3_ENDPOINT_URL}" "$${S3_ACCESS_KEY}" "$${S3_SECRET_KEY}"; do
        echo 'Waiting for MinIO...';
        sleep 1;
      done;
      mc mb --ignore-existing local/$${S3_BUCKET};
      mc anonymous set download local/$${S3_BUCKET};
      "
    restart: "no"

volumes:
  postgres_data:
  hf_models:
  s3_data:
