services:
  app:
    build:
      context: .
    image: georag-api
    depends_on:
      postgres:
        condition: service_started
      qdrant:
        condition: service_started
      minio:
        condition: service_started
    environment:
      DEV_MODE: "${DEV_MODE:-true}"
      LOG_LEVEL: "${LOG_LEVEL:-DEBUG}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      DATABASE_DSN: "${DATABASE_DSN_DOCKER:-postgresql+asyncpg://postgres:postgres@postgres:5432/georag}"
      DATABASE_ECHO: "${DATABASE_ECHO:-false}"
      S3_BUCKET: "${S3_BUCKET:-georag}"
      S3_REGION: "${S3_REGION:-us-east-1}"
      S3_ENDPOINT_URL: "${S3_ENDPOINT_URL:-http://minio:9000}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-minioadmin}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-minioadmin}"
      S3_PUBLIC_BASE_URL: "${S3_PUBLIC_BASE_URL:-http://localhost:9000/georag}"
      S3_PRESIGN_TTL: "${S3_PRESIGN_TTL:-3600}"
      S3_MAX_PARALLEL: "${S3_MAX_PARALLEL:-16}"
      STORAGE_IMAGE_SUBDIR: "${STORAGE_IMAGE_SUBDIR:-images}"
      STORAGE_FEATURE_SUBDIR: "${STORAGE_FEATURE_SUBDIR:-features}"
      STORAGE_PREVIEW_SUBDIR: "${STORAGE_PREVIEW_SUBDIR:-previews}"
      STORAGE_QUERY_SUBDIR: "${STORAGE_QUERY_SUBDIR:-queries}"
      FEATURE_CACHE_SIZE_MB: "${FEATURE_CACHE_SIZE_MB:-1536}"
      FEATURE_CACHE_ITEMS: "${FEATURE_CACHE_ITEMS:-512}"
      FEATURE_PREFETCH_LIMIT: "${FEATURE_PREFETCH_LIMIT:-16}"
      QDRANT_URL: "${QDRANT_URL:-http://qdrant:6333}"
      QDRANT_COLLECTION: "${QDRANT_COLLECTION:-georag_images}"
      QDRANT_SHARDS: "${QDRANT_SHARDS:-1}"
      QDRANT_REPLICATION: "${QDRANT_REPLICATION:-1}"
      QDRANT_ON_DISK: "${QDRANT_ON_DISK:-true}"
      FEATURE_MAX_KEYPOINTS: "${FEATURE_MAX_KEYPOINTS:-4096}"
      LOCAL_FEATURE_TYPE: "${LOCAL_FEATURE_TYPE:-superpoint_max}"
      GLOBAL_DESCRIPTOR_TYPE: "${GLOBAL_DESCRIPTOR_TYPE:-netvlad}"
      MATCHER_TYPE: "${MATCHER_TYPE:-lightglue}"
      RETRIEVAL_CANDIDATES: "${RETRIEVAL_CANDIDATES:-32}"
      GLOBAL_SCORE_WEIGHT: "${GLOBAL_SCORE_WEIGHT:-0.35}"
      LOCAL_SCORE_WEIGHT: "${LOCAL_SCORE_WEIGHT:-0.65}"
      GEOMETRY_SCORE_WEIGHT: "${GEOMETRY_SCORE_WEIGHT:-0.25}"
      MAX_SEARCH_RESULTS: "${MAX_SEARCH_RESULTS:-50}"
      POINT_CLOUD_LIMIT: "${POINT_CLOUD_LIMIT:-2048}"
      COMPUTE_DEVICE: "${COMPUTE_DEVICE:-}"
      NOMINATIM_USER_AGENT: "${NOMINATIM_USER_AGENT:-GeoRAG/1.0 (+https://example.com)}"
      NOMINATIM_TIMEOUT: "${NOMINATIM_TIMEOUT:-50}"
      MAPILLARY_TOKEN: "${MAPILLARY_TOKEN:-}"
    ports:
      - "8000:8000"
    volumes:
      - nn_models:/models
      - ./train_data:/app/train_data

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-georag}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      OLLAMA_KEEP_ALIVE: "${OLLAMA_KEEP_ALIVE:-24h}"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  qdrant:
    image: qdrant/qdrant:v1.12.3
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY:-minioadmin}"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  nn_models:
  qdrant_data:
  ollama_data:
  minio_data:
